services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: project_ambience_production
    ports:
      - "6433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-net

  redis:
    image: redis:7
    ports:
      - "7379:6379"
    networks:
      - app-net
    env_file:
      - .env

  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "7091:3000"
    volumes:
      - .:/rails
      - bundle-cache:/usr/local/bundle
    environment:
      RAILS_ENV: development
      DATABASE_URL: "postgresql://postgres:password@db:5432/project_ambience_production"
    networks:
      - app-net
    depends_on:
      - db
      - redis
    env_file:
      - .env
    command: ["bin/rails", "server", "-b", "0.0.0.0", "-p", "3000"]
  
  sneakers:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      RAILS_ENV: development
      DATABASE_URL: "postgresql://postgres:password@db:5432/project_ambience_development"
    networks:
      - app-net
    depends_on:
      - db
      - redis
    env_file:
      - .env
    command: ["bundle", "exec", "rake", "sneakers:run"]

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "7090:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_CABLE_URL=ws://api:7091/cable
    networks:
      - app-net
    depends_on:
      - api

volumes:
  db-data:
  bundle-cache:

networks:
  app-net:
