version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: project_ambience_development
    ports:
      - "5433:5432"
    volumes:
      - db-data-dev:/var/lib/postgresql/data
    networks:
      - app-net-dev

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3000"
    volumes:
      - .:/rails
      - bundle-cache:/usr/local/bundle
    environment:
      RAILS_ENV: development
      DATABASE_URL: "postgresql://postgres:password@db:5432/project_ambience_development"
    networks:
      - app-net-dev
    depends_on:
      - db
    command: ["bin/rails", "server", "-b", "0.0.0.0", "-p", "3000"]

volumes:
  db-data-dev:
  bundle-cache:

networks:
  app-net-dev:
