services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: project_ambience_development
    ports:
      - "5433:5432"
    volumes:
      - db-data-dev:/var/lib/postgresql/data
    networks:
      - app-net-dev

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - app-net-dev
    env_file:
      - .env

  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5091:3000"
    volumes:
      - .:/rails
      - bundle-cache-dev:/usr/local/bundle
    environment:
      RAILS_ENV: development
      DATABASE_URL: "postgresql://postgres:password@db:5432/project_ambience_development"
    networks:
      - app-net-dev
    depends_on:
      - db
      - redis
    env_file:
      - .env
    command: ["bin/rails", "server", "-b", "0.0.0.0", "-p", "3000"]

  sneakers:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      RAILS_ENV: development
      DATABASE_URL: "postgresql://postgres:password@db:5432/project_ambience_development"
    networks:
      - app-net-dev
    depends_on:
      - db
      - redis
    env_file:
      - .env
    command: ["bundle", "exec", "rake", "sneakers:run"]

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "5090:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_CABLE_URL=ws://128.16.12.219:5091/cable
    networks:
      - app-net-dev
    depends_on:
      - api

volumes:
  db-data-dev:
  bundle-cache-dev:

networks:
  app-net-dev:
