services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: project_ambience_development
    ports:
      - "5433:5432"
    volumes:
      - db-data-dev:/var/lib/postgresql/data
    networks:
      - app-net-dev

  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5090:3000"
    volumes:
      - .:/rails
      - bundle-cache:/usr/local/bundle
    environment:
      RAILS_ENV: development
      DATABASE_URL: "postgresql://postgres:password@db:5432/project_ambience_development"
    networks:
      - app-net-dev
    depends_on:
      - db
    command: sh -c "rm -f /rails/tmp/pids/server.pid && bin/rails server -b 0.0.0.0 -p 3000"

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - app-net-dev
    depends_on:
      - api

  rabbitmq:
    image: rabbitmq:3.12-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-net-dev

  python-worker:
    build:
      context: ./python-worker
      dockerfile: Dockerfile
    volumes:
      - ./python-worker:/app
    depends_on:
      - rabbitmq
      - api
    networks:
      - app-net-dev
    environment:
      - RAILS_API_CALLBACK_URL=http://api:3000/api/internal/results
      - HMAC_SECRET=${HMAC_SECRET}

volumes:
  db-data-dev:
  bundle-cache:

networks:
  app-net-dev:
